### ISSUE TITLE
run train.py error

### ISSUE THREAD

**Issue by Wangxuefeng92** [jinxixiang/magic_animate_unofficial#11]
hi，sir，thank your great project！I am trying your  ’train.py‘， but there exist two issues：
a.   the 'dwpose_conditions' from dwpose is numpy-type, but model need is torch-type
b. image_prompts is not used in training interface

Is there any miss in your uploaded code?

**Comment by jinxixiang** [comment]
Thank you for bringing up this issue. It appears there are some version incompatibilities within the released code. I will investigate this matter and release an updated version shortly.

**Comment by Wangxuefeng92** [comment]
thank you very much for your rely!!! I fixed these issues above and run this code. But unfortunatly，I got divergent result  in ubc fashion dataset. Is there other problem in training？

**Comment by jinxixiang** [comment]
I update the train.py

This version should work normally. 

The former version uses fine-grained image prompts during training, but it is unstable. 

We use null text prompts in the updated version, like MagicAnimate.

**Comment by Wangxuefeng92** [comment]
very appreciated for your help！thank you！

**Comment by WilliamZhaoz** [comment]
@Wangxuefeng92 Hi, I'd like to know do you use batch_size=1 or >1, I noticed that there are some comments in python file as "FIXME: only support train_batch_size=1".
