### ISSUE TITLE
OOM during infer

### ISSUE THREAD

**Issue by WilliamZhaoz** [jinxixiang/magic_animate_unofficial#12]
Thanks for your great efforts for optimize the magic animate and share the training code.
When I run the infer script in the repo, I hit a OOM error (I have 80G memory), but when I run infer script in official repo, it works well (only take about 15G memory), do you have any idea about the problem? 
Looking forward to your reply, thanks!

**Comment by jinxixiang** [comment]
Thank you. Please make sure you have torch==2.0.0+xformers==0.0.19.

I used v100 for inference and it takes 14G GPU memory.

**Comment by WilliamZhaoz** [comment]
> Thank you. Please make sure you have torch==2.0.0+xformers==0.0.19.
> 
> I used v100 for inference and it takes 14G GPU memory.

Thanks for your quick reply! It works after I update my torch version.
