### ISSUE TITLE
shouldn't finetune be true for stage 1?

### ISSUE THREAD

**Issue by jaymefosa** [jinxixiang/magic_animate_unofficial#2]
in the [aa_train_stage1.yaml](https://github.com/jinxixiang/magic_animate_unofficial/blob/main/configs/training/aa_train_stage1.yaml) config file it has: image_finetune: false

(I hastily posted this before going through the train.py in depth, maybe the answer will be in there)

**Comment by jinxixiang** [comment]
this parameter is used in animatediff, and has no effect here
